---
title: My life @ 101-Pavilions of Eau Claire
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: A review of my 1 star life @ Pavilions of Eau Claire. <br/> The trademark
  Pavilions of Eau Claire is used throughout this site by the author for the purposes
  of parody, satire, criticism, review, and news reporting. <br/> All content on this
  are the sole opinions, views and beliefs of the author and do not necessarily represent
  the views of the condo corporation, its board or any other residents.
baseurl: ''
url: ''
theme: minima
plugins:
- jekyll-feed
- jekyll-sitemap
google_analytics: G-NPPZDJGM27
