name: Spellcheck
on:
  push:
    paths:
    - '**.txt'
    - '**.html'
    - '**.md'
    - '.github/workflows/spellcheck.yaml'
jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Spellcheck Action
      uses: rojopolis/spellcheck-github-actions@0.27.0
