name: Spellcheck
on:
  push:
    paths:
    - '**.txt'
    - '**.html'
    - '**.md'
    - '.github/workflows/spellcheck.yaml'
jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Spellings
      uses: check-spelling/check-spelling@v0.0.19
